export const FALLBACK_PRODUCTS = [
  {
    id: 'fallback-1',
    nome: 'Nécessaire Personalizada',
    descricao: 'Com frase, nome ou logo gravados',
    categoria: 'Nécessaires',
    preco_por: 79.90,
    preco_de: 89.90,
    tag: 'Mais pedida',
    destaque: true,
    ativo: true,
    tall: true,
    image_url: null,
    publico: 'B2C,B2B',
    ordem: 1,
  },
  {
    id: 'fallback-2',
    nome: 'Kit Capa A5 + Porta Batom',
    descricao: 'Conjunto exclusivo em couro sintético',
    categoria: 'Kits & Conjuntos',
    preco_por: 119.90,
    preco_de: null,
    tag: null,
    destaque: true,
    ativo: true,
    tall: false,
    image_url: null,
    publico: 'B2C,B2B',
    ordem: 2,
  },
  {
    id: 'fallback-3',
    nome: 'Porta Batom Individual',
    descricao: 'Elegante e personalizado com a sua marca',
    categoria: 'Porta Batom',
    preco_por: 39.90,
    preco_de: null,
    tag: 'Corporativo',
    destaque: true,
    ativo: true,
    tall: false,
    image_url: null,
    publico: 'B2B',
    ordem: 3,
  },
  {
    id: 'fallback-4',
    nome: 'Kits & Conjuntos em Couro',
    descricao: 'Curados com detalhes dourados únicos',
    categoria: 'Kits & Conjuntos',
    preco_por: 159.90,
    preco_de: 189.90,
    tag: 'Premium',
    destaque: true,
    ativo: true,
    tall: true,
    image_url: null,
    publico: 'B2C,B2B',
    ordem: 4,
  },
  {
    id: 'fallback-5',
    nome: 'Chaveiros Personalizados',
    descricao: 'Logo em baixo relevo, ideal para empresas',
    categoria: 'Chaveiros',
    preco_por: 29.90,
    preco_de: null,
    tag: null,
    destaque: true,
    ativo: true,
    tall: false,
    image_url: null,
    publico: 'B2B',
    ordem: 5,
  },
  {
    id: 'fallback-6',
    nome: 'Kits para Eventos & Datas',
    descricao: 'Perfeito para presentear em grupo',
    categoria: 'Especial',
    preco_por: 199.90,
    preco_de: null,
    tag: 'Especial',
    destaque: true,
    ativo: true,
    tall: false,
    image_url: null,
    publico: 'B2C,B2B',
    ordem: 6,
  },
]
